ver: "v1.0.0"
readme:
  imports:
    - module: "base"
    - module: "banner"
      img:
        path: "{project}/sections/section-aiwbzongjie.md"
    - module: "datalens"
    - module: "aiwb-summary"
      ref: "{project}/sections/section-aiwbzongjie.md"
    - module: "ruiping"
      refs:
        - "{project}/sections/sections-ruiping-douxiba.md"
        - "{project}/sections/sections-ruiping-makitoid.md"
    - module: "links"
    - module: "ranking"
