config:
  title: "Awesome Iwb"
  socialLinks:
    - type: "qqGroup"
      id: "1004548404"
      url: "https://qm.qq.com/q/im8ZtJpkZy"
    - type: "telegramGroup"
      id: "awesome_iwb"
      url: "https://t.me/awesome_iwb"
  cacheOptions:
    dir: "./assets"
  refs:
    projects: "./config/aiwb.projects.yaml"
    template: "./config/aiwb.template.md"
    assetsPath: "./config/assets"
